### ISSUE TITLE
Installing without depending on nuget FNA

### ISSUE THREAD

**Issue by freeeranger** [vonderborch/Velentr.Font#18]
I'm  trying to install Velentr.Font though nuget, but I'm getting an error since it requires an FNA nuget package to be install (if I understand everything correctly). However, FNA isn't a nuget package and the link referenced in the dependency page on [nuget.org](https://www.nuget.org/packages/Velentr.Font.FNA/) is invalid (https://www.nuget.org/packages/FNA/). I've installed FNA through the recommended way on their wiki, aka through adding it as a project to your solution.

When trying to install the Velentr.Font I'm getting this error: 
`Unable to resolve dependency 'FNA'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.`

Thanks in advance!

**Comment by vonderborch** [comment]
Interesting. So, looks like I messed up some mapping in the dev environment project for FNA, but the actual nuget for the FNA code doesn't reference the FNA nuget (locally it uses the FNA repo as a submodule). There was a reference to the fnalibs nuget (which I dropped in the version of this I'll be pushing out soon).

I'll continue to look into this tomorrow since I've been having some issues with FNA recently (changed out my computer and re-installed everything).

**Comment by vonderborch** [comment]
Sorry for the late reply here, I've been pretty swamped with work + family things. I think if you clone the repo and include it as a project dependency rather than as the nuget, you should be good. I might be able to push out a version of this that ignores the dependency so it can be installed on either Monogame or FNA regardless, but I'm not sure what the timeline will end up being to do so.

**Comment by vonderborch** [comment]
Think I've got it resolved? In the middle of re-organizing a bunch of stuff so haven't done extensive tests, but lmk if it doesn't work.

**Comment by freeeranger** [comment]
I can check as soon as I have time over, not working with FNA anymore but will of course check anyways

**Comment by freeeranger** [comment]
Yup, seems to be working fine on my end. Don't know if I should close the issue though since I haven't really done any serious testing either :)

**Comment by vonderborch** [comment]
I'll close it for now at least. I plan on some big work in this repo soon(ish...depending on family and work stuffs), so at that point I'll likely be doing much more testing as well
